/* NEXO 3.1 — social layer. No toca nexo-salas. */
(function(){
  const $=id=>document.getElementById(id);
  const toast=m=>{if(window.showToast)window.showToast(m);else if($('toast')){$('toast').textContent=m;$('toast').classList.add('on');setTimeout(()=>$('toast').classList.remove('on'),2200)}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const validUuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
  let booted=false;
  const state={contacts:[],incoming:[],outgoing:[],rooms:[],invitations:[],history:[]};

  async function authUser(){
    if(typeof sb==='undefined')return null;
    const {data,error}=await sb.auth.getUser();
    if(error||!data?.user||!validUuid(data.user.id))return null;
    return data.user;
  }

  function ensureStyle(){
    if($('nexo31-style'))return;
    const s=document.createElement('style');s.id='nexo31-style';s.textContent=`
      .n31-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.n31-card{padding:24px}.n31-card h3{font-size:28px;margin:10px 0 16px}.n31-search{display:flex;gap:8px}.n31-list{display:grid;gap:10px;margin-top:14px}.n31-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.025)}.n31-main{min-width:0}.n31-title{font-weight:800}.n31-sub{font-size:12px;color:var(--muted);margin-top:4px}.n31-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.n31-divider{height:1px;background:rgba(255,255,255,.08);margin:22px 0}.n31-subhead{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:9px}.n31-note,.n31-empty{color:var(--muted);font-size:12px;line-height:1.6}.n31-status{font-size:11px;padding:5px 8px;border-radius:999px;background:rgba(77,216,255,.08);color:var(--cyan);white-space:nowrap}.n31-rooms{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.n31-room{padding:18px;border:1px solid rgba(255,255,255,.08);border-radius:16px;background:rgba(255,255,255,.025)}.n31-room-key{font:700 15px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--cyan);margin:8px 0;word-break:break-all}@media(max-width:900px){.n31-grid{grid-template-columns:1fr}.n31-rooms{grid-template-columns:1fr 1fr}}@media(max-width:600px){.n31-search{flex-direction:column}.n31-rooms{grid-template-columns:1fr}.n31-row{align-items:flex-start;flex-direction:column}}`;
    document.head.appendChild(s);
  }

  function ensureUI(){
    if($('nexo31-social'))return;
    const anchor=$('perfil')||document.querySelector('footer');if(!anchor)return;
    const sec=document.createElement('section');sec.id='nexo31-social';sec.innerHTML=`
      <div class="container"><div class="section-head"><div><div class="tag">06 — Tu red</div><h2>Contactos e<br>invitaciones.</h2></div><p class="muted">Conectá personas, administrá invitaciones y mantené tus salas sincronizadas con NEXO.</p></div>
      <div class="n31-grid">
        <article class="card n31-card" id="contactos"><div class="tag">CONTACTOS</div><h3>Encontrá personas</h3><div class="n31-search"><input id="n31ContactSearch" class="input" placeholder="Buscar por @usuario…"><button class="btn primary" id="n31ContactSearchBtn">Buscar</button></div><div id="n31SearchResults" class="n31-list"></div><div class="n31-divider"></div><div class="n31-subhead"><strong>Mis contactos</strong><button class="btn" id="n31RefreshContacts">↻ Actualizar</button></div><div id="n31ContactsList" class="n31-list"></div></article>
        <article class="card n31-card" id="invitaciones"><div class="tag">06 — Invitaciones</div><h3>Compartí tu Nexo.</h3><div id="n31InvitationsList" class="n31-list"></div><div class="n31-divider"></div><div class="n31-subhead"><strong>Nueva invitación</strong></div><select id="n31InviteContact" class="input"><option value="">Elegí un contacto…</option></select><div class="n31-actions"><button class="btn primary" id="n31SendInvite">Invitar a mi sala</button><button class="btn" id="n31RefreshInvites">↻ Actualizar</button></div><div class="n31-note">Las invitaciones se guardan en Supabase. Los invitados pueden entrar sin cuenta.</div></article>
      </div><div class="n31-divider"></div><article class="card n31-card" id="n31MyRooms"><div class="section-head"><div><div class="tag">MIS SALAS</div><h3>Salas reales</h3></div><button class="btn primary" id="n31CreateRoom">＋ Crear sala</button></div><div id="n31RoomsList" class="n31-rooms"></div></article></div>`;
    anchor.parentNode.insertBefore(sec,anchor);
  }

  function ensureHistoryUI(){
    if($('nexo31-historial'))return;
    const anchor=$('nexo31-social')||$('perfil')||document.querySelector('footer');if(!anchor)return;
    const sec=document.createElement('section');sec.id='nexo31-historial';sec.innerHTML=`<div class="container"><div class="section-head"><div><div class="tag">07 — Historial</div><h2>Tus llamadas<br>recientes.</h2></div><p class="muted">Actividad registrada por NEXO sin tocar NEXO Salas.</p></div><div class="card n31-card"><div class="n31-subhead"><strong>Actividad</strong><button class="btn" id="n31HistoryRefresh">↻ Actualizar</button></div><div id="n31HistoryList" class="n31-list"></div></div></div>`;anchor.parentNode.insertBefore(sec,anchor.nextSibling);$('n31HistoryRefresh').onclick=loadHistory;
  }

  async function loadContacts(){
    const u=await authUser();if(!u)return;
    const a=await sb.from('contacts').select('id,user_id,contact_user_id,status,created_at').eq('user_id',u.id).order('created_at',{ascending:false});
    const b=await sb.from('contacts').select('id,user_id,contact_user_id,status,created_at').eq('contact_user_id',u.id).order('created_at',{ascending:false});
    if(a.error||b.error){toast('✕ No se pudieron cargar los contactos');return;}
    const rows=[...(a.data||[]),...(b.data||[])];const ids=[...new Set(rows.flatMap(r=>[r.user_id,r.contact_user_id]).filter(id=>validUuid(id)&&id!==u.id))];
    let prof=[];if(ids.length){const q=await sb.from('profiles').select('id,username,display_name,bio').in('id',ids);if(q.error){toast('✕ '+q.error.message);return}prof=q.data||[]}
    const map=new Map(prof.map(p=>[p.id,p]));
    state.contacts=rows.filter(r=>r.status==='accepted').map(r=>({...r,profile:map.get(r.user_id===u.id?r.contact_user_id:r.user_id)}));
    state.incoming=rows.filter(r=>r.status==='pending'&&r.contact_user_id===u.id).map(r=>({...r,profile:map.get(r.user_id)}));
    state.outgoing=rows.filter(r=>r.status==='pending'&&r.user_id===u.id).map(r=>({...r,profile:map.get(r.contact_user_id)}));
    renderContacts();fillInviteContacts();
  }

  const pn=p=>p?.display_name||p?.username||'Usuario NEXO',ph=p=>p?.username?('@'+p.username):'';
  function renderContacts(){const box=$('n31ContactsList');if(!box)return;const out=[];for(const r of state.incoming)out.push(`<div class="n31-row"><div class="n31-main"><div class="n31-title">${esc(pn(r.profile))}</div><div class="n31-sub">${esc(ph(r.profile))} quiere agregarte</div></div><div class="n31-actions"><button class="btn primary" data-ca="${r.id}">Aceptar</button><button class="btn" data-cr="${r.id}">Rechazar</button></div></div>`);for(const r of state.outgoing)out.push(`<div class="n31-row"><div class="n31-main"><div class="n31-title">${esc(pn(r.profile))}</div><div class="n31-sub">${esc(ph(r.profile))} · pendiente</div></div><span class="n31-status">Pendiente</span></div>`);for(const r of state.contacts)out.push(`<div class="n31-row"><div class="n31-main"><div class="n31-title">${esc(pn(r.profile))}</div><div class="n31-sub">${esc(ph(r.profile))}</div></div><button class="btn" data-ci="${r.profile?.id||''}">Invitar</button></div>`);box.innerHTML=out.join('')||'<div class="n31-empty">Todavía no tenés contactos.</div>';box.querySelectorAll('[data-ca]').forEach(b=>b.onclick=()=>acceptContact(b.dataset.ca));box.querySelectorAll('[data-cr]').forEach(b=>b.onclick=()=>rejectContact(b.dataset.cr));box.querySelectorAll('[data-ci]').forEach(b=>b.onclick=()=>{if(b.dataset.ci&&validUuid(b.dataset.ci)){$('n31InviteContact').value=b.dataset.ci;document.getElementById('invitaciones')?.scrollIntoView({behavior:'smooth'})}});}

  function fillInviteContacts(){const sel=$('n31InviteContact');if(!sel)return;sel.innerHTML='<option value="">Elegí un contacto…</option>'+state.contacts.filter(r=>validUuid(r.profile?.id)).map(r=>`<option value="${r.profile.id}">${esc(pn(r.profile))} ${esc(ph(r.profile))}</option>`).join('');}

  async function searchProfiles(){const u=await authUser();const box=$('n31SearchResults');if(!u){toast('✓ Ingresá para buscar personas');return}const q=$('n31ContactSearch')?.value.trim().replace(/^@/,'');if(!q){toast('✕ Escribí un usuario o nombre');return}const r=await sb.from('profiles').select('id,username,display_name,bio').neq('id',u.id).or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).limit(20);if(r.error){toast('✕ '+r.error.message);return}box.innerHTML=(r.data||[]).map(p=>`<div class="n31-row"><div class="n31-main"><div class="n31-title">${esc(pn(p))}</div><div class="n31-sub">${esc(ph(p))}${p.bio?' · '+esc(p.bio):''}</div></div><button class="btn primary" data-add="${p.id}">Agregar</button></div>`).join('')||'<div class="n31-empty">No encontramos personas.</div>';box.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>sendRequest(b.dataset.add));}

  async function sendRequest(id){const u=await authUser();if(!u||!validUuid(id))return;const r=await sb.from('contacts').insert({user_id:u.id,contact_user_id:id,status:'pending'});if(r.error){toast(r.error.code==='23505'?'✕ La solicitud ya existe':'✕ '+r.error.message);return}toast('✓ Solicitud enviada');await loadContacts();}
  async function acceptContact(id){const u=await authUser();if(!u)return;const r=await sb.from('contacts').update({status:'accepted'}).eq('id',id).eq('contact_user_id',u.id);if(r.error){toast('✕ '+r.error.message);return}toast('✓ Contacto aceptado');await loadContacts();}
  async function rejectContact(id){const u=await authUser();if(!u)return;const r=await sb.from('contacts').delete().eq('id',id).eq('contact_user_id',u.id);if(r.error){toast('✕ '+r.error.message);return}toast('✓ Solicitud rechazada');await loadContacts();}

  async function loadRooms(){const u=await authUser();if(!u)return;const r=await sb.from('rooms').select('id,owner_id,room_key,name,is_personal,created_at').eq('owner_id',u.id).order('created_at',{ascending:false});if(r.error){toast('✕ '+r.error.message);return}state.rooms=r.data||[];renderRooms();}
  function renderRooms(){const box=$('n31RoomsList');if(!box)return;box.innerHTML=state.rooms.map(r=>`<div class="n31-room"><div class="tag">${r.is_personal?'PERSONAL':'SALA'}</div><h4 style="margin:8px 0">${esc(r.name)}</h4><div class="n31-room-key">${esc(r.room_key)}</div><div class="n31-actions"><button class="btn primary" data-re="${esc(r.room_key)}">Entrar</button><button class="btn" data-rc="${esc(r.room_key)}">Copiar</button></div></div>`).join('')||'<div class="n31-empty">No hay salas todavía.</div>';box.querySelectorAll('[data-re]').forEach(b=>b.onclick=()=>window.enterVideo?.(b.dataset.re));box.querySelectorAll('[data-rc]').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(b.dataset.rc).then(()=>toast('✓ Copiado')))}
  async function createRoom(){const u=await authUser();if(!u){window.openAuth?.('register');return}const key='nexo-'+u.id.replaceAll('-','').slice(0,8)+'-'+Math.random().toString(36).slice(2,7).toUpperCase();const r=await sb.from('rooms').insert({owner_id:u.id,room_key:key,name:'Nueva sala NEXO',is_personal:false}).select().single();if(r.error){toast('✕ '+r.error.message);return}window.setCurrentRoom?.(key);toast('✓ Sala creada');await loadRooms();}

  async function loadInvitations(){const u=await authUser();if(!u)return;const a=await sb.from('invitations').select('id,room_id,inviter_id,invitee_user_id,token,status,expires_at,created_at').eq('invitee_user_id',u.id).order('created_at',{ascending:false});const b=await sb.from('invitations').select('id,room_id,inviter_id,invitee_user_id,token,status,expires_at,created_at').eq('inviter_id',u.id).order('created_at',{ascending:false});if(a.error||b.error){toast('✕ No se pudieron cargar las invitaciones');return}const rows=[...(a.data||[]),...(b.data||[])];const ids=[...new Set(rows.flatMap(r=>[r.inviter_id,r.invitee_user_id]).filter(id=>validUuid(id)&&id!==u.id))];let prof=[];if(ids.length){const p=await sb.from('profiles').select('id,username,display_name').in('id',ids);prof=p.data||[]}const map=new Map(prof.map(p=>[p.id,p]));const roomIds=[...new Set(rows.map(r=>r.room_id).filter(validUuid))];let rr=[];if(roomIds.length){const q=await sb.from('rooms').select('id,room_key,name').in('id',roomIds);rr=q.data||[]}const rm=new Map(rr.map(r=>[r.id,r]));state.invitations=rows.map(r=>({...r,other:map.get(r.inviter_id===u.id?r.invitee_user_id:r.inviter_id),room:rm.get(r.room_id)}));renderInvitations();}
  function renderInvitations(){const box=$('n31InvitationsList');if(!box)return;const uPromise=authUser();uPromise.then(u=>{if(!u){box.innerHTML='<div class="n31-empty">Iniciá sesión para ver invitaciones.</div>';return}const pendingIn=state.invitations.filter(x=>x.invitee_user_id===u.id&&x.status==='pending');const pendingOut=state.invitations.filter(x=>x.inviter_id===u.id&&x.status==='pending');const parts=[...pendingIn.map(x=>`<div class="n31-row"><div class="n31-main"><div class="n31-title">${esc(pn(x.other))} te invitó</div><div class="n31-sub">${esc(x.room?.name||'Sala NEXO')} · ${esc(x.room?.room_key||'')}</div></div><div class="n31-actions"><button class="btn primary" data-ia="${x.id}">Aceptar</button><button class="btn" data-ir="${x.id}">Rechazar</button></div></div>`),...pendingOut.map(x=>`<div class="n31-row"><div class="n31-main"><div class="n31-title">Invitación enviada</div><div class="n31-sub">${esc(pn(x.other))} · ${esc(x.room?.room_key||'')}</div></div><span class="n31-status">Pendiente</span></div>`)];box.innerHTML=parts.join('')||'<div class="n31-empty">No tenés invitaciones pendientes.</div>';box.querySelectorAll('[data-ia]').forEach(b=>b.onclick=()=>updateInvite(b.dataset.ia,'accepted'));box.querySelectorAll('[data-ir]').forEach(b=>b.onclick=()=>updateInvite(b.dataset.ir,'revoked'))});}
  async function sendInvite(){const u=await authUser();if(!u)return toast('✓ Ingresá para enviar invitaciones');const cid=$('n31InviteContact')?.value;if(!validUuid(cid))return toast('✕ Elegí un contacto');const own=state.rooms.find(r=>r.is_personal)||state.rooms[0];if(!own||!validUuid(own.id))return toast('✕ No tenés una sala propia');const r=await sb.from('invitations').insert({room_id:own.id,inviter_id:u.id,invitee_user_id:cid,status:'pending'});if(r.error){toast('✕ '+r.error.message);return}toast('✓ Invitación enviada');await loadInvitations();}
  async function updateInvite(id,status){const u=await authUser();if(!u||!validUuid(id))return;const r=await sb.from('invitations').update({status}).eq('id',id).eq('invitee_user_id',u.id);if(r.error){toast('✕ '+r.error.message);return}toast(status==='accepted'?'✓ Invitación aceptada':'✓ Invitación rechazada');if(status==='accepted'){const q=await sb.from('invitations').select('room_id').eq('id',id).maybeSingle();if(q.data?.room_id){const rr=await sb.from('rooms').select('room_key').eq('id',q.data.room_id).maybeSingle();if(rr.data?.room_key)window.setCurrentRoom?.(rr.data.room_key)}}await loadInvitations();}

  async function loadHistory(){const u=await authUser();const box=$('n31HistoryList');if(!box)return;if(!u){box.innerHTML='<div class="n31-empty">Iniciá sesión para ver tu historial.</div>';return}const r=await sb.from('call_history').select('room_key,joined_at,duration_seconds,direction').eq('user_id',u.id).order('joined_at',{ascending:false}).limit(25);if(r.error){toast('✕ '+r.error.message);return}box.innerHTML=(r.data||[]).map(x=>`<div class="n31-row"><div class="n31-main"><div class="n31-title">${esc(x.room_key||'Sala NEXO')}</div><div class="n31-sub">${new Date(x.joined_at).toLocaleString('es-UY')}</div></div><span class="n31-status">${x.direction==='join'?'Entrada':'Actividad'}</span></div>`).join('')||'<div class="n31-empty">Todavía no hay llamadas registradas.</div>';}

  function bind(){
    ensureStyle();ensureUI();ensureHistoryUI();
    $('n31ContactSearchBtn')?.addEventListener('click',searchProfiles);$('n31ContactSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchProfiles()});$('n31RefreshContacts')?.addEventListener('click',loadContacts);$('n31RefreshInvites')?.addEventListener('click',loadInvitations);$('n31SendInvite')?.addEventListener('click',sendInvite);$('n31CreateRoom')?.addEventListener('click',createRoom);
    loadContacts();loadRooms();loadInvitations();loadHistory();booted=true;
  }
  async function start(){if(booted)return;bind();if(typeof sb!=='undefined')sb.auth.onAuthStateChange(()=>setTimeout(()=>{loadContacts();loadRooms();loadInvitations();loadHistory()},250));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
  window.NEXO31={loadAll:async()=>{await Promise.all([loadContacts(),loadRooms(),loadInvitations(),loadHistory()])},loadContacts,loadRooms,loadInvitations,createRoom,loadHistory};
})();
