/* NEXO 3.3 — presencia + chat privado. No modifica nexo-salas. */
(function(){
  'use strict';
  if(window.__NEXO33)return; window.__NEXO33=true;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
  const db=()=>{try{return typeof sb!=='undefined'?sb:null}catch{return null}};
  const toast=m=>typeof window.showToast==='function'?window.showToast(m):null;
  const state={me:null,contacts:[],profiles:new Map(),chatUser:null,chatChannel:null,presenceChannel:null,presence:new Map(),typingTimer:null};
  const clientKey=()=>sessionStorage.getItem('nexo_presence_key')||(sessionStorage.setItem('nexo_presence_key',(crypto.randomUUID?.()||Math.random().toString(36).slice(2)) ),sessionStorage.getItem('nexo_presence_key'));
  const display=p=>p?.display_name||p?.username||'Usuario NEXO';
  const username=p=>p?.username?'@'+p.username:'';
  function styles(){if($('n33style'))return;const s=document.createElement('style');s.id='n33style';s.textContent=`.n33-grid{display:grid;grid-template-columns:280px 1fr;gap:16px}.n33-card{padding:22px}.n33-contacts{display:grid;gap:8px}.n33-contact{width:100%;display:flex;align-items:center;gap:10px;padding:10px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.025);color:var(--text);text-align:left}.n33-contact.active{border-color:var(--cyan);background:rgba(77,216,255,.06)}.n33-dot{width:9px;height:9px;border-radius:50%;background:#59636d;flex:0 0 auto}.n33-dot.online{background:var(--green);box-shadow:0 0 10px rgba(99,230,190,.45)}.n33-chat{min-height:430px;display:flex;flex-direction:column}.n33-head{display:flex;justify-content:space-between;align-items:center;gap:10px;padding-bottom:14px;border-bottom:1px solid var(--line)}.n33-messages{flex:1;overflow:auto;padding:18px 2px;display:grid;align-content:start;gap:8px;max-height:420px}.n33-msg{max-width:76%;padding:10px 13px;border-radius:16px;line-height:1.45;font-size:14px}.n33-msg.mine{margin-left:auto;background:var(--cyan);color:#001017;border-bottom-right-radius:5px}.n33-msg.theirs{background:rgba(255,255,255,.06);border:1px solid var(--line);border-bottom-left-radius:5px}.n33-meta{font-size:10px;opacity:.65;margin-top:4px}.n33-input{display:flex;gap:8px;padding-top:12px;border-top:1px solid var(--line)}.n33-input textarea{flex:1;min-height:46px;max-height:120px;resize:vertical}.n33-typing{font-size:11px;color:var(--muted);height:18px}.n33-avatar{width:38px;height:38px;border-radius:12px;object-fit:cover;border:1px solid rgba(77,216,255,.22);background:#0e1821;display:grid;place-items:center;color:var(--cyan);font-weight:900}.n33-empty{color:var(--muted);font-size:13px;padding:18px 0}.n33-presence{font-size:12px;color:var(--muted)}@media(max-width:820px){.n33-grid{grid-template-columns:1fr}.n33-messages{max-height:360px}}`;document.head.appendChild(s)}
  async function currentUser(){const d=db();if(!d)return null;const r=await d.auth.getUser();const u=r.data?.user;state.me=u&&uuid(u.id)?u:null;return state.me}
  async function loadContacts(){if(!state.me)return;const d=db();const r=await d.from('contacts').select('user_id,contact_user_id,status').eq('status','accepted').or(`user_id.eq.${state.me.id},contact_user_id.eq.${state.me.id}`);if(r.error)return toast('✕ Contactos: '+r.error.message);const ids=[...new Set((r.data||[]).map(x=>x.user_id===state.me.id?x.contact_user_id:x.user_id).filter(uuid))];if(!ids.length){state.contacts=[];renderContacts();return}const p=await d.from('profiles').select('id,username,display_name,avatar_url,bio').in('id',ids);if(p.error)return toast('✕ Perfiles: '+p.error.message);state.contacts=p.data||[];state.contacts.forEach(x=>state.profiles.set(x.id,x));renderContacts();}
  function renderContacts(){const box=$('n33Contacts');if(!box)return;box.innerHTML=state.contacts.map(p=>{const online=state.presence.has(p.id);return `<button class="n33-contact ${state.chatUser===p.id?'active':''}" data-chat-user="${p.id}"><span class="n33-dot ${online?'online':''}"></span>${p.avatar_url?`<img class="n33-avatar" src="${esc(p.avatar_url)}" alt="" loading="lazy">`:`<span class="n33-avatar">${esc(display(p).slice(0,1).toUpperCase())}</span>`}<span><strong>${esc(display(p))}</strong><span class="muted" style="display:block;font-size:11px">${esc(username(p))}</span></span></button>`}).join('')||'<div class="n33-empty">Agregá un contacto para empezar a chatear.</div>';box.querySelectorAll('[data-chat-user]').forEach(b=>b.onclick=()=>openChat(b.dataset.chatUser));}
  function ensureUI(){if($('nexo33'))return;styles();const anchor=$('nexo312-history')||$('nexo32-profile')||$('perfil')||document.querySelector('footer');if(!anchor?.parentNode)return;const sec=document.createElement('section');sec.id='nexo33';sec.innerHTML=`<div class="container"><div class="section-head"><div><div class="tag">09 — NEXO 3.3</div><h2>Conectá en<br>tiempo real.</h2></div><p class="muted">Presencia online, chat privado y estado “escribiendo…”. La videollamada sigue separada en NEXO Salas.</p></div><div class="n33-grid"><article class="card n33-card"><div class="tag">CONTACTOS</div><h3>Ahora en NEXO</h3><div id="n33Contacts" class="n33-contacts"><div class="n33-empty">Cargando…</div></div></article><article class="card n33-card n33-chat"><div class="n33-head"><div><div class="tag">CHAT PRIVADO</div><h3 id="n33ChatTitle" style="margin:7px 0">Elegí un contacto</h3><div id="n33PresenceText" class="n33-presence">—</div></div><button class="btn" id="n33Refresh">↻</button></div><div id="n33Messages" class="n33-messages"><div class="n33-empty">Seleccioná un contacto para empezar.</div></div><div id="n33Typing" class="n33-typing"></div><div class="n33-input"><textarea id="n33Text" class="input" placeholder="Escribí un mensaje…" disabled></textarea><button id="n33Send" class="btn primary" disabled>Enviar</button></div></article></div></div>`;anchor.parentNode.insertBefore(sec,anchor.nextSibling);$('n33Refresh').onclick=async()=>{await loadContacts();if(state.chatUser)await loadMessages()};$('n33Text').addEventListener('input',handleTyping);$('n33Text').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});$('n33Send').onclick=sendMessage;}
  function presenceStart(){const d=db();if(!d||!state.me||state.presenceChannel)return;const ch=d.channel('nexo:presence');state.presenceChannel=ch;ch.on('presence',{event:'sync'},()=>{const raw=ch.presenceState();const m=new Map();Object.values(raw).flat().forEach(p=>{if(uuid(p.userId))m.set(p.userId,p)});state.presence=m;renderContacts();updatePresenceText();}).on('presence',{event:'join'},()=>{}).on('presence',{event:'leave'},()=>{}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.track({userId:state.me.id,displayName:state.me.user_metadata?.display_name||state.me.email?.split('@')[0]||'Usuario NEXO',tab:clientKey()});});}
  function updatePresenceText(){const el=$('n33PresenceText');if(!el||!state.chatUser)return;el.textContent=state.presence.has(state.chatUser)?'● En línea':'○ Desconectado';}
  function chatTopic(a,b){return 'nexo:chat:'+[a,b].sort().join(':')}
  async function openChat(id){if(!uuid(id)||!state.me)return;state.chatUser=id;renderContacts();const p=state.profiles.get(id);$('n33ChatTitle').textContent=display(p);updatePresenceText();$('n33Text').disabled=false;$('n33Send').disabled=false;await loadMessages();subscribeChat();}
  async function loadMessages(){if(!state.me||!state.chatUser)return;const d=db();const r=await d.from('messages').select('id,sender_id,recipient_id,body,created_at,read_at').or(`and(sender_id.eq.${state.me.id},recipient_id.eq.${state.chatUser}),and(sender_id.eq.${state.chatUser},recipient_id.eq.${state.me.id})`).order('created_at',{ascending:true}).limit(200);if(r.error)return toast('✕ Chat: '+r.error.message);const box=$('n33Messages');box.innerHTML=(r.data||[]).map(renderMessage).join('')||'<div class="n33-empty">Todavía no hay mensajes.</div>';box.scrollTop=box.scrollHeight;const unread=(r.data||[]).filter(x=>x.recipient_id===state.me.id&&!x.read_at).map(x=>x.id);if(unread.length)await d.from('messages').update({read_at:new Date().toISOString()}).in('id',unread).eq('recipient_id',state.me.id);}
  function renderMessage(m){const mine=m.sender_id===state.me.id;const when=new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});return `<div class="n33-msg ${mine?'mine':'theirs'}"><div>${esc(m.body).replace(/\n/g,'<br>')}</div><div class="n33-meta">${when}${mine&&m.read_at?' · leído':''}</div></div>`;}
  function subscribeChat(){if(state.chatChannel){try{db()?.removeChannel(state.chatChannel)}catch{}}if(!state.me||!state.chatUser)return;const d=db(),ch=d.channel(chatTopic(state.me.id,state.chatUser));state.chatChannel=ch;ch.on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`recipient_id=eq.${state.me.id}`},payload=>{if(payload.new?.sender_id===state.chatUser){loadMessages()}}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'messages',filter:`sender_id=eq.${state.me.id}`},payload=>{if(payload.new?.recipient_id===state.chatUser)loadMessages()}).on('broadcast',{event:'typing'},({payload})=>{if(payload?.userId===state.chatUser){$('n33Typing').textContent=payload.typing?`${display(state.profiles.get(state.chatUser))} está escribiendo…`:'';if(payload.typing)setTimeout(()=>{$('n33Typing').textContent=''},1800)}}).subscribe();}
  async function sendMessage(){if(!state.me||!state.chatUser)return;const ta=$('n33Text'),body=ta.value.trim();if(!body)return;ta.value='';const d=db();const r=await d.from('messages').insert({sender_id:state.me.id,recipient_id:state.chatUser,body}).select('id,sender_id,recipient_id,body,created_at,read_at').single();if(r.error){toast('✕ '+r.error.message);return}renderAfterSend(r.data);await sendTyping(false);}
  function renderAfterSend(m){const box=$('n33Messages');const empty=box.querySelector('.n33-empty');if(empty)empty.remove();box.insertAdjacentHTML('beforeend',renderMessage(m));box.scrollTop=box.scrollHeight;}
  async function sendTyping(typing){const ch=state.chatChannel;if(!ch||!state.me)return;await ch.send({type:'broadcast',event:'typing',payload:{userId:state.me.id,typing}});}
  function handleTyping(){sendTyping(true);clearTimeout(state.typingTimer);state.typingTimer=setTimeout(()=>sendTyping(false),900);}
  async function boot(){ensureUI();state.me=await currentUser();if(!state.me){$('n33Contacts').innerHTML='<div class="n33-empty">Iniciá sesión para usar el chat.</div>';return}await loadContacts();presenceStart();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
