/* NEXO 3.2 — perfil y presencia. No modifica nexo-salas. */
(function(){
  'use strict';
  if(window.__NEXO32)return; window.__NEXO32=true;
  const $=id=>document.getElementById(id);
  const toast=m=>{if(typeof window.showToast==='function')return window.showToast(m);const t=$('toast');if(!t)return;t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2200)};
  const valid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  let me=null, profile=null;
  function display(){return profile?.display_name||me?.email?.split('@')[0]||'Usuario NEXO'}
  function username(){return profile?.username?'@'+profile.username:''}
  function avatar(){return profile?.avatar_url||''}
  function setAvatar(el){if(!el)return;const src=avatar();if(src){el.style.backgroundImage=`url(${JSON.stringify(src)})`;el.style.backgroundSize='cover';el.textContent=''}else{el.style.backgroundImage='';el.textContent=(display()[0]||'N').toUpperCase()}}
  async function load(){if(typeof sb==='undefined')return;const u=(await sb.auth.getUser()).data?.user;if(!u||!valid(u.id))return;me=u;const q=await sb.from('profiles').select('id,username,display_name,avatar_url,bio').eq('id',u.id).maybeSingle();if(!q.error)profile=q.data;render()}
  function render(){const btn=$('authBtn');if(btn){btn.textContent=display();btn.title=username()||me?.email||''}const side=$('sideName');if(side)side.textContent=display();const mail=$('sideMail');if(mail)mail.textContent=username()||me?.email||'';const welcome=$('welcomeText');if(welcome)welcome.textContent='Hola, '+display()+' 👋';setAvatar($('sideAvatar'));setAvatar($('bigAvatar'));const p=$('profileName');if(p)p.textContent=display();const u=$('profileUsername');if(u)u.textContent=username();const a=$('profileAvatar');setAvatar(a);if($('presenceStatus'))$('presenceStatus').textContent='● En línea'}
  function ensure(){if($('nexo32-profile'))return;const anchor=$('perfil')||document.querySelector('footer');if(!anchor?.parentNode)return;const s=document.createElement('section');s.id='nexo32-profile';s.innerHTML=`<div class="container"><div class="section-head"><div><div class="tag">08 — Identidad</div><h2>Tu perfil,<br>tu NEXO.</h2></div><p class="muted">Personalizá cómo te ven otros usuarios. Tu identidad se guarda en Supabase.</p></div><div class="card" style="padding:24px;display:grid;grid-template-columns:180px 1fr;gap:24px;align-items:start"><div style="text-align:center"><div id="profileAvatar" class="avatar" style="width:120px;height:120px;border-radius:32px;margin:auto;font-size:38px">N</div><div id="presenceStatus" class="badge" style="margin-top:12px">● En línea</div></div><div><div class="tag">MI CUENTA</div><h3 id="profileName" style="font-size:30px;margin:10px 0 4px">Usuario NEXO</h3><div id="profileUsername" class="muted">@usuario</div><p id="profileBio" class="muted" style="line-height:1.6;margin-top:12px">Tu perfil NEXO.</p><div class="actions" style="margin-top:18px"><button class="btn primary" id="editProfileBtn">Editar perfil</button><button class="btn" id="copyProfileBtn">Copiar perfil</button></div></div></div></div>`;anchor.parentNode.insertBefore(s,anchor);const st=document.createElement('style');st.textContent=`@media(max-width:600px){#nexo32-profile .card{grid-template-columns:1fr!important;text-align:center}}.n32-modal{position:fixed;inset:0;z-index:140;background:rgba(0,0,0,.72);backdrop-filter:blur(10px);display:grid;place-items:center;padding:18px}.n32-box{width:min(480px,100%);background:#0c1117;border:1px solid var(--line);border-radius:22px;padding:24px}.n32-form{display:grid;gap:12px}.n32-form label{font-size:12px;color:var(--muted)}.n32-form input,.n32-form textarea{margin-top:5px;width:100%;padding:12px;background:#080c10;color:var(--text);border:1px solid var(--line);border-radius:13px}.n32-form textarea{min-height:90px;resize:vertical}`;document.head.appendChild(st);$('editProfileBtn').onclick=openEdit;$('copyProfileBtn').onclick=copyProfile}
  function openEdit(){if(!$('n32modal')){const m=document.createElement('div');m.id='n32modal';m.className='n32-modal';m.innerHTML=`<div class="n32-box"><div class="actions" style="justify-content:space-between"><div><div class="tag">EDITAR PERFIL</div><h3 style="margin:8px 0">Tu identidad NEXO</h3></div><button class="btn" id="n32Close">Cerrar</button></div><div class="n32-form"><label>Nombre visible<input id="n32Name" value="${esc(profile?.display_name||'')}"></label><label>Usuario<input id="n32Username" value="${esc(profile?.username||'')}" placeholder="usuario"></label><label>Foto (URL)<input id="n32Avatar" value="${esc(profile?.avatar_url||'')}" placeholder="https://..."></label><label>Biografía<textarea id="n32Bio">${esc(profile?.bio||'')}</textarea></label><button class="btn primary" id="n32Save">Guardar cambios</button></div></div>`;document.body.appendChild(m);$('n32Close').onclick=()=>m.remove();$('n32Save').onclick=save}else $('n32modal').classList.remove('hidden')}
  async function save(){if(!me)return toast('✓ Iniciá sesión');const payload={display_name:$('n32Name').value.trim()||'Usuario NEXO',username:$('n32Username').value.trim().replace(/^@/,''),avatar_url:$('n32Avatar').value.trim()||null,bio:$('n32Bio').value.trim()||null,updated_at:new Date().toISOString()};if(!/^[a-zA-Z0-9._-]{3,30}$/.test(payload.username))return toast('✕ Usuario inválido');const q=await sb.from('profiles').update(payload).eq('id',me.id);if(q.error){toast(q.error.code==='23505'?'✕ Ese usuario ya existe':'✕ '+q.error.message);return}profile={...profile,...payload};render();$('n32modal')?.remove();toast('✓ Perfil actualizado')}
  async function copyProfile(){const text=`${display()} ${username()} — NEXO`;try{await navigator.clipboard.writeText(text);toast('✓ Perfil copiado')}catch{toast(text)}}
  function start(){ensure();load();if(typeof sb!=='undefined')sb.auth.onAuthStateChange(()=>setTimeout(load,150))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
