/* NEXO 3.1.2 performance layer. NEVER touches nexo-salas. */
(function(){
  'use strict';
  if(window.__NEXO312_LOADED)return;
  window.__NEXO312_LOADED=true;
  const $=id=>document.getElementById(id);
  const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast=m=>{if(typeof window.showToast==='function'){window.showToast(m);return}const t=$('toast');if(!t)return;t.textContent=m;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2200)};
  const db=()=>{try{return typeof sb!=='undefined'?sb:null}catch{return null}};
  const go=id=>$(id)?.scrollIntoView({behavior:'smooth',block:'start'});
  const state={contacts:[],incoming:[],outgoing:[],rooms:[],invites:[],history:[],notifications:[]};
  let me=null,authBound=false,dataLoaded=false,observerStarted=false,favoritesCache=null,favoritesAt=0;
  const name=()=>me?.user_metadata?.display_name||me?.email?.split('@')[0]||'Usuario NEXO';
  const enterRoom=key=>{if(key)location.href='https://rodrigomidon04-ui.github.io/nexo-salas/?sala='+encodeURIComponent(key)+'&nombre='+encodeURIComponent(name())+'&auto=1'};
  async function refreshUser(){const d=db();if(!d){me=null;return null}const {data,error}=await d.auth.getUser();me=!error&&uuid(data?.user?.id)?data.user:null;return me}
  function styles(){if($('nexo312-style'))return;const s=document.createElement('style');s.id='nexo312-style';s.textContent='.n312-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.n312-card{padding:24px}.n312-list{display:grid;gap:10px;margin-top:14px}.n312-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.025)}.n312-main{min-width:0}.n312-title{font-weight:800}.n312-sub{font-size:12px;color:var(--muted);margin-top:4px}.n312-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.n312-empty{color:var(--muted);font-size:13px;padding:14px 0}.n312-status{font-size:11px;padding:5px 8px;border-radius:999px;background:rgba(77,216,255,.08);color:var(--cyan);white-space:nowrap}.n312-fav{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.04);color:var(--text);padding:9px 12px;border-radius:999px}.n312-fav.on{color:var(--cyan);border-color:var(--cyan)}.n312-notify{position:relative}.n312-count{position:absolute;top:-5px;right:-3px;min-width:18px;height:18px;border-radius:999px;background:var(--cyan);color:#001017;font-size:10px;font-weight:900;display:grid;place-items:center}.n312-panel{position:fixed;top:68px;right:20px;width:min(390px,calc(100vw - 28px));max-height:70vh;overflow:auto;padding:16px;background:#0c1117;border:1px solid var(--line);border-radius:18px;box-shadow:0 25px 80px rgba(0,0,0,.55);z-index:130}.n312-item{padding:12px;border-bottom:1px solid rgba(255,255,255,.07)}.n312-item.unread{background:rgba(77,216,255,.05);border-radius:12px}.n312-tools{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.n312-meta{font-size:12px;color:var(--muted);margin-top:4px}@media(max-width:900px){.n312-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
  function sections(){if(!$('nexo312-social')){const anchor=$('perfil')||document.querySelector('footer');if(anchor?.parentNode){const sec=document.createElement('section');sec.id='nexo312-social';sec.innerHTML='<div class="container"><div class="section-head"><div><div class="tag">06 — Tu red</div><h2>Contactos e<br>invitaciones.</h2></div><p class="muted">Conectá personas, administrá invitaciones y mantené tus salas sincronizadas con NEXO.</p></div><div class="n312-grid"><article class="card n312-card" id="contactos"><div class="tag">CONTACTOS</div><h3>Encontrá personas</h3><div class="inputline"><input id="n312Search" class="input" placeholder="Buscar por @usuario…"><button class="btn primary" id="n312SearchBtn">Buscar</button></div><div id="n312Results" class="n312-list"></div><div style="height:1px;background:var(--line);margin:20px 0"></div><div class="n312-tools"><strong>Mis contactos</strong><button class="btn" id="n312RefreshContacts">↻ Actualizar</button></div><div id="n312Contacts" class="n312-list"><div class="n312-empty">Iniciá sesión para cargar contactos.</div></div></article><article class="card n312-card" id="invitaciones"><div class="tag">INVITACIONES</div><h3>Entrá y compartí salas</h3><div id="n312Invites" class="n312-list"><div class="n312-empty">Iniciá sesión para ver invitaciones.</div></div><div style="height:1px;background:var(--line);margin:20px 0"></div><strong>Nueva invitación</strong><select id="n312InviteContact" class="input" style="margin-top:10px"><option value="">Elegí un contacto…</option></select><button class="btn primary" id="n312SendInvite" style="margin-top:10px">Invitar a mi sala</button></article></div><div style="height:1px;background:var(--line);margin:28px 0"></div><article class="card n312-card"><div class="n312-tools"><div><div class="tag">SALAS REALES</div><h3 style="margin:8px 0">Mis salas</h3></div><button class="btn primary" id="n312CreateRoom">＋ Crear sala</button></div><div id="n312Rooms" class="n312-list"><div class="n312-empty">Iniciá sesión para ver tus salas.</div></div></article></div></section>';anchor.parentNode.insertBefore(sec,anchor)}}if(!$('nexo312-history')){const anchor=$('nexo312-social')||$('perfil')||document.querySelector('footer');if(anchor?.parentNode){const sec=document.createElement('section');sec.id='nexo312-history';sec.innerHTML='<div class="container"><div class="section-head"><div><div class="tag">07 — Historial</div><h2>Tus llamadas<br>recientes.</h2></div><p class="muted">NEXO registra tus entradas. La videollamada continúa en NEXO Salas sin modificaciones.</p></div><div class="card n312-card"><div class="n312-tools"><strong>Actividad</strong><button class="btn" id="n312RefreshHistory">↻ Actualizar</button></div><div id="n312History" class="n312-list"><div class="n312-empty">Iniciá sesión para ver tu historial.</div></div></div></div>';anchor.parentNode.insertBefore(sec,anchor.nextSibling)}}}
  function bell(){const nav=document.querySelector('.nav-inner');if(!nav||$('n312Bell'))return;const b=document.createElement('button');b.id='n312Bell';b.className='btn ghost n312-notify';b.innerHTML='🔔<span id="n312Count" class="n312-count hidden">0</span>';const p=document.createElement('div');p.id='n312Panel';p.className='n312-panel hidden';p.innerHTML='<div class="n312-tools"><div><div class="tag">NEXO</div><h3 style="margin:7px 0">Notificaciones</h3></div><button class="btn" id="n312MarkAll">Marcar todo</button></div><div id="n312Notifications" class="n312-list"></div>';nav.insertBefore(b,nav.querySelector('#authBtn'));document.body.appendChild(p);b.onclick=()=>p.classList.toggle('hidden');document.addEventListener('click',e=>{if(e.target!==b&&!p.contains(e.target))p.classList.add('hidden')},{passive:true});$('n312MarkAll').onclick=markAll}
  function bind(){if(window.__NEXO312_BOUND)return;window.__NEXO312_BOUND=true;$('n312SearchBtn')?.addEventListener('click',searchPeople);$('n312Search')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchPeople()});$('n312RefreshContacts')?.addEventListener('click',loadContacts);$('n312SendInvite')?.addEventListener('click',sendInvite);$('n312CreateRoom')?.addEventListener('click',createRoom);$('n312RefreshHistory')?.addEventListener('click',loadHistory)}
  const pn=p=>p?.display_name||p?.username||'Usuario NEXO',ph=p=>p?.username?('@'+p.username):'';
  async function loadContacts(){if(!me)return;const d=db(),r=await d.from('contacts').select('id,user_id,contact_user_id,status,created_at').or(`user_id.eq.${me.id},contact_user_id.eq.${me.id}`).order('created_at',{ascending:false});if(r.error){toast('✕ Contactos: '+r.error.message);return}const rows=r.data||[],ids=[...new Set(rows.flatMap(x=>[x.user_id,x.contact_user_id]).filter(x=>uuid(x)&&x!==me.id))];let ps=[];if(ids.length){const q=await d.from('profiles').select('id,username,display_name,bio').in('id',ids);if(q.error){toast('✕ Perfiles: '+q.error.message);return}ps=q.data||[]}const map=new Map(ps.map(x=>[x.id,x]));state.contacts=rows.filter(x=>x.status==='accepted').map(x=>({...x,p:map.get(x.user_id===me.id?x.contact_user_id:x.user_id)}));state.incoming=rows.filter(x=>x.status==='pending'&&x.contact_user_id===me.id).map(x=>({...x,p:map.get(x.user_id)}));state.outgoing=rows.filter(x=>x.status==='pending'&&x.user_id===me.id).map(x=>({...x,p:map.get(x.contact_user_id)}));renderContacts();fillInviteContacts()}
  function renderContacts(){const box=$('n312Contacts');if(!box)return;let h='';for(const x of state.incoming)h+=`<div class="n312-row"><div><div class="n312-title">${esc(pn(x.p))}</div><div class="n312-sub">${esc(ph(x.p))} · quiere agregarte</div></div><div class="n312-actions"><button class="btn primary" data-ca="${x.id}">Aceptar</button><button class="btn" data-cr="${x.id}">Rechazar</button></div></div>`;for(const x of state.outgoing)h+=`<div class="n312-row"><div><div class="n312-title">${esc(pn(x.p))}</div><div class="n312-sub">${esc(ph(x.p))}</div></div><span class="n312-status">Pendiente</span></div>`;for(const x of state.contacts)h+=`<div class="n312-row"><div><div class="n312-title">${esc(pn(x.p))}</div><div class="n312-sub">${esc(ph(x.p))}</div></div><button class="btn" data-ci="${x.p?.id||''}">Invitar</button></div>`;box.innerHTML=h||'<div class="n312-empty">Todavía no tenés contactos.</div>';box.querySelectorAll('[data-ca]').forEach(b=>b.onclick=()=>acceptContact(b.dataset.ca));box.querySelectorAll('[data-cr]').forEach(b=>b.onclick=()=>rejectContact(b.dataset.cr));box.querySelectorAll('[data-ci]').forEach(b=>b.onclick=()=>{$('n312InviteContact').value=b.dataset.ci;go('invitaciones')})}
  function fillInviteContacts(){const s=$('n312InviteContact');if(!s)return;s.innerHTML='<option value="">Elegí un contacto…</option>'+state.contacts.filter(x=>uuid(x.p?.id)).map(x=>`<option value="${x.p.id}">${esc(pn(x.p))} ${esc(ph(x.p))}</option>`).join('')}
  async function searchPeople(){if(!me){toast('✓ Ingresá para buscar personas');return}const q=$('n312Search')?.value.trim().replace(/^@/,'');const out=$('n312Results');if(!q){out.innerHTML='<div class="n312-empty">Escribí un nombre o @usuario.</div>';return}const d=db(),r=await d.from('profiles').select('id,username,display_name,bio').neq('id',me.id).or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).limit(20);if(r.error){toast('✕ Buscar: '+r.error.message);return}out.innerHTML=(r.data||[]).map(p=>`<div class="n312-row"><div><div class="n312-title">${esc(pn(p))}</div><div class="n312-sub">${esc(ph(p))}${p.bio?' · '+esc(p.bio):''}</div></div><button class="btn primary" data-add="${p.id}">Agregar</button></div>`).join('')||'<div class="n312-empty">No encontramos personas.</div>';out.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>sendContact(b.dataset.add))}
  async function sendContact(id){if(!me||!uuid(id)||id===me.id)return;const d=db(),[a,b]=await Promise.all([d.from('contacts').select('id,status').eq('user_id',me.id).eq('contact_user_id',id).limit(1),d.from('contacts').select('id,status').eq('user_id',id).eq('contact_user_id',me.id).limit(1)]);if(a.error||b.error){toast('✕ No se pudo comprobar el contacto');return}const existing=[...(a.data||[]),...(b.data||[])];if(existing.some(x=>x.status==='accepted')){toast('✓ Ya son contactos');return}if(existing.some(x=>x.status==='pending')){toast('✓ Ya existe una solicitud pendiente');return}const r=await d.from('contacts').insert({user_id:me.id,contact_user_id:id,status:'pending'});if(r.error){toast(r.error.code==='23505'?'✓ Ya existe una solicitud':'✕ '+r.error.message);return}toast('✓ Solicitud enviada');await loadContacts();await loadNotifications()}
  async function acceptContact(id){if(!me||!uuid(id))return;const r=await db().from('contacts').update({status:'accepted'}).eq('id',id).eq('contact_user_id',me.id);if(r.error){toast('✕ '+r.error.message);return}toast('✓ Contacto aceptado');await loadContacts();await loadNotifications()}
  async function rejectContact(id){if(!me||!uuid(id))return;const r=await db().from('contacts').delete().eq('id',id).eq('contact_user_id',me.id);if(r.error){toast('✕ '+r.error.message);return}toast('✓ Solicitud rechazada');await loadContacts();await loadNotifications()}
  async function loadFavorites(force=false){if(!me)return new Set();const now=Date.now();if(!force&&favoritesCache&&now-favoritesAt<15000)return favoritesCache;const r=await db().from('favorites').select('room_id').eq('user_id',me.id);if(r.error){toast('✕ Favoritos: '+r.error.message);return new Set()}favoritesCache=new Set((r.data||[]).map(x=>x.room_id));favoritesAt=now;return favoritesCache}
  async function toggleFavorite(id,b){if(!me||!uuid(id))return;const d=db(),fav=await loadFavorites();const r=fav.has(id)?await d.from('favorites').delete().eq('user_id',me.id).eq('room_id',id):await d.from('favorites').insert({user_id:me.id,room_id:id});if(r.error){toast('✕ '+r.error.message);return}favoritesCache=null;await loadRooms();toast(fav.has(id)?'✓ Quitado de favoritos':'✓ Agregado a favoritos')}
  async function loadRooms(){if(!me)return;const d=db(),r=await d.from('rooms').select('id,owner_id,room_key,name,is_personal,created_at').eq('owner_id',me.id).order('created_at',{ascending:false}),fav=await loadFavorites(true);if(r.error){toast('✕ Salas: '+r.error.message);return}state.rooms=r.data||[];const box=$('n312Rooms');if(!box)return;box.innerHTML=state.rooms.length?state.rooms.map(x=>`<div class="n312-row"><div><div class="tag">${x.is_personal?'PERSONAL':'SALA'}</div><div class="n312-title">${esc(x.name)}</div><div class="n312-sub">${esc(x.room_key)}</div></div><div class="n312-actions"><button class="btn primary" data-enter="${esc(x.room_key)}">Entrar</button><button class="n312-fav ${fav.has(x.id)?'on':''}" data-fav="${x.id}">${fav.has(x.id)?'★ Favorito':'☆ Favorito'}</button></div></div>`).join(''):'<div class="n312-empty">No hay salas todavía.</div>';box.querySelectorAll('[data-enter]').forEach(b=>b.onclick=()=>enterRoom(b.dataset.enter));box.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.fav,b))}
  async function createRoom(){if(!me){toast('✓ Ingresá para crear una sala');return}const base=name().toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,16)||'usuario',key=`nexo-${base}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,r=await db().from('rooms').insert({owner_id:me.id,room_key:key,name:'Nueva sala NEXO',is_personal:false}).select().single();if(r.error){toast('✕ Crear sala: '+r.error.message);return}toast('✓ Nueva sala creada');await loadRooms()}
  async function loadInvites(){if(!me)return;const d=db(),r=await d.from('invitations').select('id,room_id,inviter_id,invitee_user_id,token,status,expires_at,created_at').or(`inviter_id.eq.${me.id},invitee_user_id.eq.${me.id}`).order('created_at',{ascending:false}).limit(50);if(r.error){toast('✕ Invitaciones: '+r.error.message);return}const rows=r.data||[],ids=[...new Set(rows.flatMap(x=>[x.inviter_id,x.invitee_user_id]).filter(x=>uuid(x)&&x!==me.id))],rmids=[...new Set(rows.map(x=>x.room_id).filter(uuid))],[profiles,rooms]=await Promise.all([ids.length?d.from('profiles').select('id,username,display_name').in('id',ids):Promise.resolve({data:[]}),rmids.length?d.from('rooms').select('id,room_key,name').in('id',rmids):Promise.resolve({data:[]})]),pmap=new Map((profiles.data||[]).map(x=>[x.id,x])),rmap=new Map((rooms.data||[]).map(x=>[x.id,x]));state.invites=rows.map(x=>({...x,p:pmap.get(x.inviter_id===me.id?x.invitee_user_id:x.inviter_id),room:rmap.get(x.room_id)}));renderInvites()}
  function renderInvites(){const box=$('n312Invites');if(!box)return;const incoming=state.invites.filter(x=>x.invitee_user_id===me.id&&x.status==='pending'),outgoing=state.invites.filter(x=>x.inviter_id===me.id&&x.status==='pending'),h=[...incoming.map(x=>`<div class="n312-row"><div><div class="n312-title">${esc(pn(x.p))} te invitó</div><div class="n312-sub">${esc(x.room?.name||'Sala NEXO')} · ${esc(x.room?.room_key||'')}</div></div><div class="n312-actions"><button class="btn primary" data-ia="${x.id}">Aceptar</button><button class="btn" data-ir="${x.id}">Rechazar</button></div></div>`),...outgoing.map(x=>`<div class="n312-row"><div><div class="n312-title">Invitación enviada</div><div class="n312-sub">${esc(pn(x.p))} · ${esc(x.room?.room_key||'')}</div></div><span class="n312-status">Pendiente</span></div>`)];box.innerHTML=h.join('')||'<div class="n312-empty">No tenés invitaciones pendientes.</div>';box.querySelectorAll('[data-ia]').forEach(b=>b.onclick=()=>updateInvite(b.dataset.ia,'accepted'));box.querySelectorAll('[data-ir]').forEach(b=>b.onclick=()=>updateInvite(b.dataset.ir,'revoked'))}
  async function sendInvite(){if(!me){toast('✓ Ingresá para enviar invitaciones');return}const cid=$('n312InviteContact')?.value;if(!uuid(cid))return toast('✕ Elegí un contacto');const own=state.rooms.find(x=>x.is_personal)||state.rooms[0];if(!own)return toast('✕ No tenés una sala propia');const r=await db().from('invitations').insert({room_id:own.id,inviter_id:me.id,invitee_user_id:cid,status:'pending'});if(r.error){toast('✕ '+r.error.message);return}toast('✓ Invitación enviada');await loadInvites();await loadNotifications()}
  async function updateInvite(id,status){if(!me||!uuid(id))return;const r=await db().from('invitations').update({status}).eq('id',id).eq('invitee_user_id',me.id);if(r.error){toast('✕ '+r.error.message);return}toast(status==='accepted'?'✓ Invitación aceptada':'✓ Invitación rechazada');if(status==='accepted'){const q=await db().from('invitations').select('room_id').eq('id',id).maybeSingle();if(q.data?.room_id){const rr=await db().from('rooms').select('room_key').eq('id',q.data.room_id).maybeSingle();if(rr.data?.room_key)window.setCurrentRoom?.(rr.data.room_key)}}await loadInvites();await loadNotifications()}
  async function loadNotifications(){if(!me)return;const r=await db().from('notifications').select('id,type,title,body,read_at,created_at').eq('user_id',me.id).order('created_at',{ascending:false}).limit(30);if(r.error){toast('✕ Notificaciones: '+r.error.message);return}state.notifications=r.data||[];const count=state.notifications.filter(x=>!x.read_at).length,c=$('n312Count');if(c){c.textContent=String(count);c.classList.toggle('hidden',count===0)}const box=$('n312Notifications');if(!box)return;box.innerHTML=state.notifications.length?state.notifications.map(x=>`<div class="n312-item ${x.read_at?'':'unread'}" data-n="${x.id}"><strong>${esc(x.title)}</strong><div class="n312-sub">${esc(x.body||'')}</div><div class="n312-sub">${esc(new Date(x.created_at).toLocaleString('es-UY'))}</div></div>`).join(''):'<div class="n312-empty">No tenés notificaciones.</div>';box.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>readNotification(b.dataset.n))}
  async function readNotification(id){if(!me||!uuid(id))return;await db().from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',me.id);await loadNotifications()}
  async function markAll(){if(!me)return;await db().from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',me.id).is('read_at',null);await loadNotifications()}
  async function loadHistory(){const box=$('n312History');if(!box)return;if(!me){box.innerHTML='<div class="n312-empty">Iniciá sesión para ver tu historial.</div>';return}const r=await db().from('call_history').select('room_key,joined_at,duration_seconds,direction').eq('user_id',me.id).order('joined_at',{ascending:false}).limit(25);if(r.error){toast('✕ Historial: '+r.error.message);return}box.innerHTML=(r.data||[]).map(x=>`<div class="n312-row"><div><div class="n312-title">${esc(x.room_key||'Sala NEXO')}</div><div class="n312-meta">${esc(new Date(x.joined_at).toLocaleString('es-UY'))}</div></div><span class="n312-status">${x.direction==='join'?'Entrada':'Actividad'}</span></div>`).join('')||'<div class="n312-empty">Todavía no hay llamadas registradas.</div>'}
  async function loadCore(){if(dataLoaded||!me)return;dataLoaded=true;await Promise.all([loadContacts(),loadRooms(),loadInvites(),loadNotifications(),loadHistory()])}
  function observe(){if(observerStarted)return;observerStarted=true;const target=$('nexo312-social')||$('nexo312-history');if(!target)return;const io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){loadCore();io.disconnect()}},{rootMargin:'350px'});io.observe(target)}
  async function boot(){styles();sections();bell();bind();observe();await refreshUser();if(me&&!authBound&&db()){authBound=true;db().auth.onAuthStateChange((_event,session)=>{me=uuid(session?.user?.id)?session.user:null;dataLoaded=false;favoritesCache=null;favoritesAt=0;if(me)loadCore();else state.contacts=[]})}}
  const start=()=>window.requestIdleCallback?requestIdleCallback(boot,{timeout:1200}):setTimeout(boot,350);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.NEXO31={loadAll:loadCore,loadContacts,loadRooms,loadInvitations:loadInvites,createRoom,loadHistory};
})();