/* NEXO 3.1.1 complete social layer. NEVER touches nexo-salas. */
(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const toast=m=>{if(typeof window.showToast==='function')window.showToast(m);else if($('toast')){$('toast').textContent=m;$('toast').classList.add('on');setTimeout(()=>$('toast').classList.remove('on'),2200)}};
  const db=()=>{try{return typeof sb!=='undefined'?sb:null}catch{return null}};
  const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
  const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
  let me=null;
  const state={contacts:[],incoming:[],outgoing:[],rooms:[],invites:[],history:[],notifications:[]};
  async function refreshUser(){const d=db();if(!d){me=null;return null}const r=await d.auth.getUser();me=uuid(r?.data?.user?.id)?r.data.user:null;return me}
  function displayName(){return me?.user_metadata?.display_name||me?.email?.split('@')[0]||'Usuario NEXO'}
  function enterRoom(key){if(!key)return;window.location.href=`https://rodrigomidon04-ui.github.io/nexo-salas/?sala=${encodeURIComponent(key)}&nombre=${encodeURIComponent(displayName())}&auto=1`}
  function styles(){if($('nexo311-style'))return;const s=document.createElement('style');s.id='nexo311-style';s.textContent=`.n311-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.n311-card{padding:24px}.n311-list{display:grid;gap:10px;margin-top:14px}.n311-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:13px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:rgba(255,255,255,.025)}.n311-main{min-width:0}.n311-title{font-weight:800}.n311-sub{font-size:12px;color:var(--muted);margin-top:4px}.n311-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.n311-empty{color:var(--muted);font-size:13px;padding:14px 0}.n311-status{font-size:11px;padding:5px 8px;border-radius:999px;background:rgba(77,216,255,.08);color:var(--cyan);white-space:nowrap}.n311-fav{border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.04);color:var(--text);padding:9px 12px;border-radius:999px}.n311-fav.on{color:var(--cyan);border-color:var(--cyan)}.n311-notify-btn{position:relative}.n311-count{position:absolute;top:-5px;right:-3px;min-width:18px;height:18px;border-radius:999px;background:var(--cyan);color:#001017;font-size:10px;font-weight:900;display:grid;place-items:center}.n311-panel{position:fixed;top:68px;right:20px;width:min(390px,calc(100vw - 28px));max-height:70vh;overflow:auto;padding:16px;background:#0c1117;border:1px solid var(--line);border-radius:18px;box-shadow:0 25px 80px rgba(0,0,0,.55);z-index:130}.n311-item{padding:12px;border-bottom:1px solid rgba(255,255,255,.07)}.n311-item:last-child{border-bottom:0}.n311-item.unread{background:rgba(77,216,255,.05);border-radius:12px}.n311-tools{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.n311-history-meta{font-size:12px;color:var(--muted);margin-top:4px}.n311-note{font-size:12px;color:var(--muted);line-height:1.6}@media(max-width:900px){.n311-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function ensureSections(){
    if(!$('n311-social')){const anchor=$('perfil')||document.querySelector('footer');if(anchor?.parentNode){const sec=document.createElement('section');sec.id='n311-social';sec.innerHTML=`<div class="container"><div class="section-head"><div><div class="tag">06 — Tu red</div><h2>Contactos e<br>invitaciones.</h2></div><p class="muted">Conectá personas, administrá invitaciones y mantené tus salas sincronizadas con NEXO.</p></div><div class="n311-grid"><article class="card n311-card" id="contactos"><div class="tag">CONTACTOS</div><h3>Encontrá personas</h3><div class="inputline"><input id="n311Search" class="input" placeholder="Buscar por @usuario…"><button class="btn primary" id="n311SearchBtn">Buscar</button></div><div id="n311Results" class="n311-list"></div><div style="height:1px;background:var(--line);margin:20px 0"></div><div class="n311-tools"><strong>Mis contactos</strong><button class="btn" id="n311RefreshContacts">↻ Actualizar</button></div><div id="n311Contacts" class="n311-list"></div></article><article class="card n311-card" id="invitaciones"><div class="tag">INVITACIONES</div><h3>Entrá y compartí salas</h3><div id="n311Invites" class="n311-list"></div><div style="height:1px;background:var(--line);margin:20px 0"></div><strong>Nueva invitación</strong><select id="n311InviteContact" class="input" style="margin-top:10px"><option value="">Elegí un contacto…</option></select><button class="btn primary" id="n311SendInvite" style="margin-top:10px">Invitar a mi sala</button></article></div><div style="height:1px;background:var(--line);margin:28px 0"></div><article class="card n311-card"><div class="n311-tools"><div><div class="tag">SALAS REALES</div><h3 style="margin:8px 0">Mis salas</h3></div><button class="btn primary" id="n311CreateRoom">＋ Crear sala</button></div><div id="n311Rooms" class="n311-list"></div></article></div></section>`;anchor.parentNode.insertBefore(sec,anchor)}}
    if(!$('n311-history')){const anchor=$('n311-social')||$('perfil')||document.querySelector('footer');if(anchor?.parentNode){const sec=document.createElement('section');sec.id='n311-history';sec.innerHTML=`<div class="container"><div class="section-head"><div><div class="tag">07 — Historial</div><h2>Tus llamadas<br>recientes.</h2></div><p class="muted">NEXO registra tus entradas. La videollamada sigue ejecutándose en NEXO Salas sin modificaciones.</p></div><div class="card n311-card"><div class="n311-tools"><strong>Actividad</strong><button class="btn" id="n311RefreshHistory">↻ Actualizar</button></div><div id="n311History" class="n311-list"></div></div></div>`;anchor.parentNode.insertBefore(sec,anchor.nextSibling)}}
  }
  function ensureBell(){const nav=document.querySelector('.nav-inner');if(!nav||$('n311Bell'))return;const b=document.createElement('button');b.id='n311Bell';b.className='btn ghost n311-notify-btn';b.innerHTML='🔔<span id="n311Count" class="n311-count hidden">0</span>';const p=document.createElement('div');p.id='n311Panel';p.className='n311-panel hidden';p.innerHTML='<div class="n311-tools"><div><div class="tag">NEXO</div><h3 style="margin:7px 0">Notificaciones</h3></div><button class="btn" id="n311MarkAll">Marcar todo</button></div><div id="n311Notifications" class="n311-list"></div>';nav.insertBefore(b,nav.querySelector('#authBtn'));document.body.appendChild(p);b.onclick=()=>p.classList.toggle('hidden');document.addEventListener('click',e=>{if(e.target!==b&&!p.contains(e.target))p.classList.add('hidden')});$('n311MarkAll').onclick=markAllNotifications}
  const pn=p=>p?.display_name||p?.username||'Usuario NEXO',ph=p=>p?.username?('@'+p.username):'';
  async function loadContacts(){const d=db();if(!d||!me)return;const r=await d.from('contacts').select('id,user_id,contact_user_id,status,created_at').or(`user_id.eq.${me.id},contact_user_id.eq.${me.id}`).order('created_at',{ascending:false});if(r.error){toast('✕ Contactos: '+r.error.message);return}const rows=r.data||[];const ids=[...new Set(rows.flatMap(x=>[x.user_id,x.contact_user_id]).filter(x=>uuid(x)&&x!==me.id))];let ps=[];if(ids.length){const q=await d.from('profiles').select('id,username,display_name,bio').in('id',ids);if(q.error){toast('✕ Perfiles: '+q.error.message);return}ps=q.data||[]}const map=new Map(ps.map(x=>[x.id,x]));state.contacts=rows.filter(x=>x.status==='accepted').map(x=>({...x,p:map.get(x.user_id===me.id?x.contact_user_id:x.user_id)}));state.incoming=rows.filter(x=>x.status==='pending'&&x.contact_user_id===me.id).map(x=>({...x,p:map.get(x.user_id)}));state.outgoing=rows.filter(x=>x.status==='pending'&&x.user_id===me.id).map(x=>({...x,p:map.get(x.contact_user_id)}));renderContacts();fillInviteContacts()}
  function renderContacts(){const box=$('n311Contacts');if(!box)return;let h='';for(const x of state.incoming)h+=`<div class="n311-row"><div><div class="n311-title">${esc(pn(x.p))}</div><div class="n311-sub">${esc(ph(x.p))} · quiere agregarte</div></div><div class="n311-actions"><button class="btn primary" data-ca="${x.id}">Aceptar</button><button class="btn" data-cr="${x.id}">Rechazar</button></div></div>`;for(const x of state.outgoing)h+=`<div class="n311-row"><div><div class="n311-title">${esc(pn(x.p))}</div><div class="n311-sub">${esc(ph(x.p))}</div></div><span class="n311-status">Pendiente</span></div>`;for(const x of state.contacts)h+=`<div class="n311-row"><div><div class="n311-title">${esc(pn(x.p))}</div><div class="n311-sub">${esc(ph(x.p))}</div></div><button class="btn" data-ci="${x.p?.id||''}">Invitar</button></div>`;box.innerHTML=h||'<div class="n311-empty">Todavía no tenés contactos.</div>';box.querySelectorAll('[data-ca]').forEach(b=>b.onclick=()=>acceptContact(b.dataset.ca));box.querySelectorAll('[data-cr]').forEach(b=>b.onclick=()=>rejectContact(b.dataset.cr));box.querySelectorAll('[data-ci]').forEach(b=>b.onclick=()=>{$('n311InviteContact').value=b.dataset.ci;go('invitaciones')})}
  function fillInviteContacts(){const s=$('n311InviteContact');if(!s)return;s.innerHTML='<option value="">Elegí un contacto…</option>'+state.contacts.filter(x=>uuid(x.p?.id)).map(x=>`<option value="${x.p.id}">${esc(pn(x.p))} ${esc(ph(x.p))}</option>`).join('')}
  async function searchPeople(){const d=db();if(!d||!me){toast('✓ Ingresá para buscar personas');return}const q=$('n311Search')?.value.trim().replace(/^@/,'');const out=$('n311Results');if(!q){out.innerHTML='<div class="n311-empty">Escribí un nombre o @usuario.</div>';return}const r=await d.from('profiles').select('id,username,display_name,bio').neq('id',me.id).or(`username.ilike.%${q}%,display_name.ilike.%${q}%`).limit(20);if(r.error){toast('✕ Buscar: '+r.error.message);return}out.innerHTML=(r.data||[]).map(p=>`<div class="n311-row"><div><div class="n311-title">${esc(pn(p))}</div><div class="n311-sub">${esc(ph(p))}${p.bio?' · '+esc(p.bio):''}</div></div><button class="btn primary" data-add="${p.id}">Agregar</button></div>`).join('')||'<div class="n311-empty">No encontramos personas.</div>';out.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>sendContact(b.dataset.add))}
  async function sendContact(id){const d=db();if(!d||!me||!uuid(id)||id===me.id)return;const r=await d.from('contacts').insert({user_id:me.id,contact_user_id:id,status:'pending'});if(r.error){toast(r.error.code==='23505'?'✕ Ya existe una solicitud':'✕ '+r.error.message);return}toast('✓ Solicitud enviada');loadContacts();loadNotifications()}
  async function acceptContact(id){const d=db();if(!d||!me||!uuid(id))return;const r=await d.from('contacts').update({status:'accepted'}).eq('id',id).eq('contact_user_id',me.id);if(r.error){toast('✕ '+r.error.message);return}toast('✓ Contacto aceptado');loadContacts();loadNotifications()}
  async function rejectContact(id){const d=db();if(!d||!me||!uuid(id))return;const r=await d.from('contacts').delete().eq('id',id).eq('contact_user_id',me.id);if(r.error){toast('✕ '+r.error.message);return}toast('✓ Solicitud rechazada');loadContacts();loadNotifications()}
  async function loadFavorites(){const d=db();if(!d||!me)return new Set();const r=await d.from('favorites').select('room_id').eq('user_id',me.id);if(r.error){toast('✕ Favoritos: '+r.error.message);return new Set()}return new Set((r.data||[]).map(x=>x.room_id))}
  async function toggleFavorite(id,b){const d=db();if(!d||!me||!uuid(id))return;const fav=await loadFavorites();if(fav.has(id)){const r=await d.from('favorites').delete().eq('user_id',me.id).eq('room_id',id);if(r.error){toast('✕ '+r.error.message);return}b.classList.remove('on');b.textContent='☆ Favorito';toast('✓ Quitado de favoritos')}else{const r=await d.from('favorites').insert({user_id:me.id,room_id:id});if(r.error){toast('✕ '+r.error.message);return}b.classList.add('on');b.textContent='★ Favorito';toast('✓ Agregado a favoritos')}}
  async function loadRooms(){const d=db();if(!d||!me)return;const r=await d.from('rooms').select('id,owner_id,room_key,name,is_personal,created_at').eq('owner_id',me.id).order('created_at',{ascending:false});if(r.error){toast('✕ Salas: '+r.error.message);return}state.rooms=r.data||[];const fav=await loadFavorites();const box=$('n311Rooms');if(!box)return;box.innerHTML=state.rooms.length?state.rooms.map(x=>`<div class="n311-row"><div><div class="tag">${x.is_personal?'PERSONAL':'SALA'}</div><div class="n311-title">${esc(x.name)}</div><div class="n311-sub">${esc(x.room_key)}</div></div><div class="n311-actions"><button class="btn primary" data-enter="${esc(x.room_key)}">Entrar</button><button class="n311-fav ${fav.has(x.id)?'on':''}" data-fav="${x.id}">${fav.has(x.id)?'★ Favorito':'☆ Favorito'}</button></div></div>`).join(''):'<div class="n311-empty">No hay salas todavía.</div>';box.querySelectorAll('[data-enter]').forEach(b=>b.onclick=()=>enterRoom(b.dataset.enter));box.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.fav,b))}
  async function createRoom(){const d=db();if(!d||!me){toast('✓ Ingresá para crear una sala');return}const base=displayName().toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,16)||'usuario';const key=`nexo-${base}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;const r=await d.from('rooms').insert({owner_id:me.id,room_key:key,name:'Nueva sala NEXO',is_personal:false}).select().single();if(r.error){toast('✕ Crear sala: '+r.error.message);return}toast('✓ Nueva sala creada');loadRooms()}
  async function loadInvites(){const d=db();if(!d||!me)return;const r=await d.from('invitations').select('id,room_id,inviter_id,invitee_user_id,token,status,expires_at,created_at').or(`inviter_id.eq.${me.id},invitee_user_id.eq.${me.id}`).order('created_at',{ascending:false}).limit(50);if(r.error){toast('✕ Invitaciones: '+r.error.message);return}const rows=r.data||[];const ids=[...new Set(rows.flatMap(x=>[x.inviter_id,x.invitee_user_id]).filter(x=>uuid(x)&&x!==me.id))];let ps=[];if(ids.length){const p=await d.from('profiles').select('id,username,display_name').in('id',ids);ps=p.data||[]}const rmids=[...new Set(rows.map(x=>x.room_id).filter(uuid))];let rms=[];if(rmids.length){const q=await d.from('rooms').select('id,room_key,name').in('id',rmids);rms=q.data||[]}const pmap=new Map(ps.map(x=>[x.id,x]));const rmap=new Map(rms.map(x=>[x.id,x]));state.invites=rows.map(x=>({...x,p:pmap.get(x.inviter_id===me.id?x.invitee_user_id:x.inviter_id),room:rmap.get(x.room_id)}));renderInvites()}
  function renderInvites(){const box=$('n311Invites');if(!box)return;const incoming=state.invites.filter(x=>x.invitee_user_id===me.id&&x.status==='pending');const outgoing=state.invites.filter(x=>x.inviter_id===me.id&&x.status==='pending');let h='';for(const x of incoming)h+=`<div class="n311-row"><div><div class="n311-title">${esc(pn(x.p))} te invitó</div><div class="n311-sub">${esc(x.room?.name||'Sala NEXO')} · ${esc(x.room?.room_key||'')}</div></div><div class="n311-actions"><button class="btn primary" data-ia="${x.id}">Aceptar</button><button class="btn" data-ir="${x.id}">Rechazar</button></div></div>`;for(const x of outgoing)h+=`<div class="n311-row"><div><div class="n311-title">Invitación enviada a ${esc(pn(x.p))}</div><div class="n311-sub">${esc(x.room?.name||'Sala NEXO')}</div></div><span class="n311-status">Pendiente</span></div>`;box.innerHTML=h||'<div class="n311-empty">No tenés invitaciones pendientes.</div>';box.querySelectorAll('[data-ia]').forEach(b=>b.onclick=()=>updateInvite(b.dataset.ia,'accepted'));box.querySelectorAll('[data-ir]').forEach(b=>b.onclick=()=>updateInvite(b.dataset.ir,'revoked'))}
  async function sendInvite(){const d=db();if(!d||!me)return;const cid=$('n311InviteContact')?.value;if(!uuid(cid)){toast('✕ Elegí un contacto');return}const own=state.rooms.find(x=>x.is_personal)||state.rooms[0];if(!own){toast('✕ No tenés una sala propia');return}const r=await d.from('invitations').insert({room_id:own.id,inviter_id:me.id,invitee_user_id:cid,status:'pending'});if(r.error){toast('✕ '+r.error.message);return}toast('✓ Invitación enviada');loadInvites();loadNotifications()}
  async function updateInvite(id,status){const d=db();if(!d||!me||!uuid(id))return;const r=await d.from('invitations').update({status}).eq('id',id).eq('invitee_user_id',me.id).select('room_id').single();if(r.error){toast('✕ '+r.error.message);return}toast(status==='accepted'?'✓ Invitación aceptada':'✓ Invitación rechazada');loadInvites();loadNotifications()}
  async function loadNotifications(){const d=db();if(!d||!me)return;const r=await d.from('notifications').select('id,type,title,body,read_at,created_at').eq('user_id',me.id).order('created_at',{ascending:false}).limit(30);if(r.error){toast('✕ Notificaciones: '+r.error.message);return}state.notifications=r.data||[];const unread=state.notifications.filter(x=>!x.read_at).length;const c=$('n311Count');if(c){c.textContent=String(unread);c.classList.toggle('hidden',unread===0)}const box=$('n311Notifications');if(!box)return;box.innerHTML=state.notifications.length?state.notifications.map(x=>`<div class="n311-item ${x.read_at?'':'unread'}" data-n="${x.id}"><strong>${esc(x.title)}</strong><div class="n311-sub">${esc(x.body||'')}</div><div class="n311-sub">${esc(new Date(x.created_at).toLocaleString('es-UY'))}</div></div>`).join(''):'<div class="n311-empty">No tenés notificaciones.</div>';box.querySelectorAll('[data-n]').forEach(b=>b.onclick=()=>readNotification(b.dataset.n))}
  async function readNotification(id){const d=db();if(!d||!me||!uuid(id))return;await d.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',me.id);loadNotifications()}
  async function markAllNotifications(){const d=db();if(!d||!me)return;await d.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',me.id).is('read_at',null);loadNotifications()}
  async function loadHistory(){const d=db();if(!d||!me)return;const r=await d.from('call_history').select('room_key,joined_at,duration_seconds,direction').eq('user_id',me.id).order('joined_at',{ascending:false}).limit(50);if(r.error){toast('✕ Historial: '+r.error.message);return}state.history=r.data||[];const box=$('n311History');if(!box)return;box.innerHTML=state.history.length?state.history.map(x=>{const dt=new Date(x.joined_at);return `<div class="n311-row"><div><div class="n311-title">${esc(x.room_key||'Sala NEXO')}</div><div class="n311-history-meta">${esc(isNaN(dt)?x.joined_at:dt.toLocaleString('es-UY'))} · ${esc(x.duration_seconds?Math.round(x.duration_seconds/60)+' min':'Entrada registrada')}</div></div><span class="n311-status">${x.direction==='join'?'Entrada':'Actividad'}</span></div>`}).join(''):'<div class="n311-empty">Todavía no hay llamadas registradas.</div>'}
  function bind(){ $('n311SearchBtn')?.addEventListener('click',searchPeople);$('n311Search')?.addEventListener('keydown',e=>{if(e.key==='Enter')searchPeople()});$('n311RefreshContacts')?.addEventListener('click',loadContacts);$('n311SendInvite')?.addEventListener('click',sendInvite);$('n311CreateRoom')?.addEventListener('click',createRoom);$('n311RefreshHistory')?.addEventListener('click',loadHistory); }
  async function boot(){styles();ensureSections();ensureBell();await refreshUser();if(!me)return;bind();await Promise.all([loadContacts(),loadRooms(),loadInvites(),loadNotifications(),loadHistory()]);const d=db();if(d)d.auth.onAuthStateChange(async()=>{await refreshUser();if(me){bind();loadContacts();loadRooms();loadInvites();loadNotifications();loadHistory()}})}
  const start=()=>setTimeout(boot,700);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
